# llmops-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: llmops-service
spec:
  selector:
    app: llmops  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
